# Generated by Django 5.1.1 on 2024-10-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0012_alter_shegarlandform_qamaa_qophaef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='Mallattoo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='aanaa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='kan_qophesse',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='lakk_adda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='suura_iddoo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
