# Generated by Django 5.1.1 on 2024-10-23 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0014_alter_shegarlandform_suura_iddoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shegarlandform',
            name='guyya_galmae',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
