# Generated by Django 5.1.1 on 2024-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0015_shegarlandform_guyya_galmae'),
    ]

    operations = [
        migrations.AddField(
            model_name='shegarlandform',
            name='ragaittin_bahi_tae',
            field=models.ImageField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
    ]
