# Generated by Django 5.1.1 on 2024-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0016_shegarlandform_ragaittin_bahi_tae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='ragaittin_bahi_tae',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
