# Generated by Django 5.1.1 on 2024-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0017_alter_shegarlandform_ragaittin_bahi_tae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='aanaa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='magaalaa',
            field=models.CharField(choices=[('Sululta', 'Sululta'), ('M/abbichuu', 'M/abbichuu'), ('LXLD', 'LXLD'), ('K/Jiddaa', 'K/Jiddaa'), ('K/faccee', 'K/faccee'), ('Galaan', 'Galaan'), ('Furii', 'Furii'), ('G/Guddaa', 'G/Guddaa'), ('Sabbataa', 'Sabbataa'), ('M/Nonnoo', 'M/Nonnoo'), ('G/Gujee', 'G/gujee'), ('Burrayyu', 'Burrayyu')], max_length=50),
        ),
    ]
