# Generated by Django 5.1.1 on 2024-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0019_rename_suura_iddoo_shegarlandform_ragaa_biroo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='balina_lafa',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='magaalaa',
            field=models.CharField(choices=[('Sulultaa', 'Sulultaa'), ('M/Abbichuu', 'M/Abbichuu'), ('L/Xafoo L/Dadhii', 'L/Xafoo L/Dadhii'), ('K/Jiddaa', 'K/Jiddaa'), ('K/faccee', 'K/faccee'), ('Galaan', 'Galaan'), ('Furii', 'Furii'), ('G/Guddaa', 'G/Guddaa'), ('Sabbataa', 'Sabbataa'), ('M/Nonnoo', 'M/Nonnoo'), ('G/Gujee', 'G/Gujee'), ('Burrayyuu', 'Burrayyuu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='tajajila_iddo',
            field=models.CharField(choices=[('Adminstration/AD/', 'Adminstration/AD/'), ('Commercial/CO/', 'Commercial/CO/'), ('Eco_Tourism/RE-5/', 'Eco_Tourism/RE-5/'), ('Formal Green', 'Formal Green'), ('Recreational & Environmental/RE/', 'Recreational & Environmental/RE/'), ('Open Spaces and Sport Centers', 'Open Spaces and Sport Centers'), ('Pure Residence/R/', 'Pure Residence/R/'), ('Mixid Residence/R-2/', 'Mixid Residence/R-2/'), ('Manufacturing and Storage/P-1/', 'Manufacturing and Storage/P-1/'), ('Social Service/S/', 'Social Service/S/'), ('Special Function', 'Special Function'), ('Special residence', 'Special residence'), ('Transport', 'Transport'), ('Urban Agriculture/UA/', 'Urban Agriculture'), ('Logestic and Free Trade Zone', 'Logestic and Free Trade Zone'), ('River and Arteficial Lake', 'River and Arteficial Lake'), ('High Density Mixed Residence', 'High Density Mixed Residence')], max_length=60),
        ),
    ]
