# Generated by Django 5.1.1 on 2024-10-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0020_alter_shegarlandform_balina_lafa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='bal_lafa_bahi_tae',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='bal_lafa_hafe',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
