# Generated by Django 5.1.1 on 2024-10-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0021_alter_shegarlandform_bal_lafa_bahi_tae_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shegarlandform',
            old_name='aanaa',
            new_name='Aanaa',
        ),
        migrations.RenameField(
            model_name='shegarlandform',
            old_name='magaalaa',
            new_name='Kutaamagaalaa',
        ),
    ]
